# Generated by Django 3.1 on 2023-01-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('ground_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('underground_station', models.CharField(max_length=100)),
                ('photo_url', models.ImageField(upload_to='static/media/grounds-images/')),
                ('sport_type', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('free_area', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=200)),
                ('created', models.TimeField(auto_now_add=True)),
                ('author_name', models.CharField(max_length=150)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.ground')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
