# Generated by Django 3.1 on 2022-08-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220829_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='photo_url',
            field=models.ImageField(upload_to='static/media/user-images/'),
        ),
    ]
