# Generated by Django 3.1 on 2022-11-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220830_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_info_id',
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='SportType',
        ),
    ]
