# Generated by Django 3.1 on 2022-11-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
